### ISSUE TITLE
Infinite knockback

### ISSUE THREAD

**Issue by Petrica81** [widdrr/MateyBA#53]
Steps to reproduce:
-Get in the way of the rat and let him push you.
-Now you will be pushed in that direction even if you are no longer near the rat.

**Comment by widdrr** [comment]
Known Issue, should be fixed once we implement custom collision with enemy hitboxes (taking damage & knockback)
If issue still persists we'll look for a fix.

**Comment by widdrr** [comment]
Was fixed in the meantime by other PR's
